version: "3.3"


services:
  app:
    image: rohitankolnerkargamma/email-newsletter-manager:latest
    container_name: email-newsletter-manager
    ports:
      - "8000:8000"
    env_file:
      - .env